abb:
  email: andrew25447@gmail.com
  password: mastaP93$mastaP93$

tg:
  bot-token: 8503619675:AAEmjCI7O5HqBP7cMbrQh5NieYFnRcIOUVU

  pinnacle-only-chat-id: -1003635285069
  all-others-chat-id: -1003784513956
